### ISSUE TITLE
Error code: 1101

### ISSUE THREAD

**Issue by bsiegelwax** [Qiskit-Partners/mthree#128]
I have a local version of https://github.com/iccmr-quantum/QuSing that suddenly stopped working. I apologize for not copying down the exact error message, but there was an import error that was resolved by running a pip update. But, now the error is:

~\AppData\Local\Temp/ipykernel_17056/431539747.py in generate_note(transition_matrix, qubits, dictionary_key, backend, unique_notes, shots)
    117         mit.cals_from_system(qubits=assignment, shots=shots)
    118         raw_counts = result.get_counts(qc)
--> 119         m3_quasi = mit.apply_correction(raw_counts, assignment)
    120         counts = str(max(m3_quasi, key=m3_quasi.get)) # In case of shots > 1, find the result with the highest count.
    121         #counts = str(max(result.get_counts(qc)))

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mthree\mitigation.py in apply_correction(self, counts, qubits, distance, method, max_iter, tol, return_mitigation_overhead, details)
    377 
    378             quasi_out.append(
--> 379                 self._apply_correction(cnts, qubits=qubits[idx],
    380                                        distance=distance,
    381                                        method=method,

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mthree\mitigation.py in _apply_correction(self, counts, qubits, distance, method, max_iter, tol, return_mitigation_overhead, details)
    429 
    430         # Check if no cals done yet
--> 431         if self.single_qubit_cals is None:
    432             warnings.warn('No calibration data. Calibrating: {}'.format(qubits))
    433             self._grab_additional_cals(qubits, method=self.cal_method)

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mthree\mitigation.py in __getattribute__(self, attr)
     70         if attr in __dict__:
     71             if attr in ['single_qubit_cals']:
---> 72                 self._thread_check()
     73         return super().__getattribute__(attr)
     74 

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mthree\mitigation.py in _thread_check(self)
    642             self._thread = None
    643         if self._job_error:
--> 644             raise self._job_error  # pylint: disable=raising-bad-type
    645 
    646 

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mthree\mitigation.py in _job_thread(job, mit, method, qubits, num_cal_qubits, cal_strings)
    656     """
    657     try:
--> 658         res = job.result()
    659     # pylint: disable=broad-except
    660     except Exception as error:

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\qiskit\providers\ibmq\job\ibmqjob.py in result(self, timeout, wait, partial, refresh)
    288                 else:
    289                     error_message = ": " + error_message
--> 290                 raise IBMQJobFailureError(
    291                     'Unable to retrieve result for job {}. Job has failed{}'.format(
    292                         self.job_id(), error_message))

IBMQJobFailureError: 'Unable to retrieve result for job 631882bd89d4a56f5aa2c52f. Job has failed: QObj does not conform to the schema. Error code: 1101.'

**Comment by nonhermitian** [comment]
Hmm this is curious.  I have no idea why the Qobj would be malformed, especially because all the Qobj generation is done in the IBMQ provider not M3.

Looking at the error log though does seem to suggest that you are not calibrating the mitigator before applying the correction:

> 430 # Check if no cals done yet
--> 431 if self.single_qubit_cals is None:

May want to double check that.  Regardless though, that should no throw an error either.

**Comment by bsiegelwax** [comment]
This worked all throughout testing:

        mit = mthree.M3Mitigation(backend)
        mit.cals_from_system(qubits=assignment, shots=shots)
        raw_counts = result.get_counts(qc)
        m3_quasi = mit.apply_correction(raw_counts, assignment)
        counts = str(max(m3_quasi, key=m3_quasi.get))

**Comment by nonhermitian** [comment]
Closing as stale.  Feel free to re-open if still needed.
