### ISSUE TITLE
Facing issues when using mthree package for measurement error mitigation

### ISSUE THREAD

**Issue by biswajitpaul18** [Qiskit-Partners/mthree#180]
I am trying to use the mthree package for measurement error mitigation. When I am using the backend "Qasm simulator" the code is running smoothly, but when using "BraketLocalBackend" a backend of qiskit_braket_provider, getting an error in the line **"mit.cals_from_system(mappings)"** and the error is "ValueError: Circuit must have instructions to run on a device". How can I fix this issue?

<

    trans_circ = transpile(circuit, backend=device)
    mappings = mthree.utils.final_measurement_mapping(trans_circ)
    
    
    
    result = device.run(trans_circ, shots=5000).result()
    results=result.get_counts()
    
    r1 = list(results.keys())
    r2 = list(results.values())
    print(r1)
    print(r2)
    
    
    mit = mthree.M3Mitigation(device)
    mit.cals_from_system(mappings)
>

**Comment by nonhermitian** [comment]
So I am not sure what the Braket backend is expecting here. M3 will try to submit Qiskit calibration circuits that match the width of the target device. 

Also, not sure if you are doing noise modeling or not. If not, there is no benefit from M3, as there is no measurement error, and only deviations due to finite sampling.

**Comment by nonhermitian** [comment]
Closing as stale.  Feel free to re-open if needed.

**Comment by biswajitpaul18** [comment]
I have access to AWS Braket and I am attempting to run my code on Rigetti Aspen-M-3. However, I am encountering errors when using the mthree package for readout error mitigation. Here, I have attached the code and the error in a text file.

<
import qiskit_braket_provider
from qiskit.visualization import plot_histogram
import mthree
from braket.aws import AwsDevice
from qiskit_braket_provider import AWSBraketProvider

circuit = QuantumCircuit(2)
circuit.h(0)
circuit.cx(0,1)
circuit.measure_all()

provider = AWSBraketProvider()
device = provider.get_backend("Aspen-M-3")

mit = mthree.M3Mitigation(system=device)
trans_circ = transpile(circuit, backend = device, coupling_map=[[0,1]])
mappings = mthree.utils.final_measurement_mapping(trans_circ)
mit.cals_from_system(mappings,shots=1000)

task = device.run(trans_circ, shots=1000).result()
result = task.get_counts()
r1 = list(result.keys())
r2 = list(result.values())


err_mitigated_result = mit.apply_correction(result, mappings)
r1_mitigated = list(err_mitigated_result.keys())
r2_mitigated = list(err_mitigated_result.values())

plot_histogram([result,err_mitigated_result])
>
[error.txt](https://github.com/Qiskit-Partners/mthree/files/11859536/error.txt)

**Comment by nonhermitian** [comment]
I do not have access to Braket-based devices. However, it looks like the circuits do not have any instructions, which is a bit odd.  One would have to see what the circuits look like from M3.  e.g. see what the circuits here: https://github.com/Qiskit-Partners/mthree/blob/03638d91ca3faec73f6c5dd4cd364368503a80b5/mthree/mitigation.py#L379 look like

**Comment by nonhermitian** [comment]
Closing as stale.  Feel free to re-open if needed.
