### ISSUE TITLE
Expectation of operator specified as dictionary fails

### ISSUE THREAD

**Issue by kevinsung** [Qiskit-Partners/mthree#83]
Setup:
```python
import numpy as np
import mthree
from qiskit import Aer, QuantumCircuit

backend = backend = Aer.get_backend("statevector_simulator")
mit = mthree.M3Mitigation(backend)
mit.cals_from_system(range(2))

circuit = QuantumCircuit(2)
circuit.rx(np.pi / 4, 0)
circuit.rx(np.pi / 2, 1)
circuit.measure_all()

counts = backend.run(circuit, shots=1000).result().get_counts()
quasis = mit.apply_correction(counts, range(2))
```
Passing strings works:
```python
print(quasis.expval('00'))
print(quasis.expval('ZI'))
```
```
0.419
0.7020000000000001
```
Passing dictionary fails for second example:
```python
print(quasis.expval({'00': 1}))
print(quasis.expval({'ZI': 1}))
```
```
0.419
0.0
```
Passing float fails:
```python
print(quasis.expval({'00': 0.5}))
```
```
0.0
```

mthree version: 13b941f5d0517c63276970e53e08ce5a3941456f
Python version: 3.8.12
Operating system: Arch Linux

**Comment by kevinsung** [comment]
Oops, posted too early, I will edit opening post.

**Comment by nonhermitian** [comment]
Dict format is only for specifying diagonal operators in terms of their bitstrings and probabilities.  It does not work with operators. 

The other behavior is odd will have to see what is causing it.

**Comment by kevinsung** [comment]
> Dict format is only for specifying diagonal operators in terms of their bitstrings and probabilities. It does not work with operators.

Ah, I see. This is not documented anywhere as far as I can tell, but it should be. The example at https://qiskit.org/documentation/partners/mthree/expvals.html is ambiguous as to whether the keys of the dictionary must be restricted to bitstrings, or whether `Z` and `I` are allowed. I think that in the context, one might easily assume the latter, like I did.

**Comment by nonhermitian** [comment]
I guess I was not expecting to have an user use a dict of operator strings.  But I did add clarification into the docs for this.
